# Generic HTTP request
LOG_GENERIC = 'GENERIC'

# Registration
LOG_CATEGORY_REGISTRATION = 'REGISTRATION'
LOG_EVENT_LOGIN = 'LOGIN'
LOG_EVENT_LOGOUT = 'LOGOUT'
LOG_EVENT_SIGNUP = 'SIGNUP'

# Management
LOG_CATEGORY_MANAGEMENT = 'MANAGEMENT'
LOG_EVENT_DATABASE = 'DATABASE'
LOG_EVENT_DATABASE_USER = 'DATABASE_USER'
LOG_EVENT_POINTS = 'POINTS'
LOG_EVENT_ANNOUNCEMENTS = 'ANNOUNCEMENTS'
LOG_EVENT_EVENTS = 'EVENTS'

# Social network
LOG_CATEGORY_SOCIAL = 'SOCIAL'
LOG_EVENT_MEMBERS_SEARCH = 'MEMBERS_SEARCH'

# User actions
LOG_CATEGORY_USER = 'USER'
LOG_EVENT_FOLLOW = 'FOLLOW'
LOG_EVENT_UNFOLLOW = 'UNFOLLOW'
